config:
  logging:
    file: ./logs/app.log
    level: DEBUG
  name: BW_limited
  outline:
    countries:
    - BW
    - ZM
    - ZW
    years:
    - 2030
    - 2031
    - 2032
    - 2033
    - 2034
    - 2035
    - 2036
    - 2037
    - 2038
    - 2039
    - 2040
    - 2041
    - 2042
    - 2043
    - 2044
    - 2045
    - 2046
    - 2047
    - 2048
    - 2049
    - 2050
    data_file_path: ./osemosys_data/input_data/TEMBA_SSP4-60.xlsx
    fuel_code_file_path: ./osemosys_data/fuelcodes(in).csv
    tech_code_file_path: ./osemosys_data/techcodes(in).csv
    representation_per_year: ['S1D1', 'S1D2', 'S2D1', 'S2D2', 'S3D1', 'S3D2', 'S4D1', 'S4D2'] # Representations inside an year
    timeout_time_step: 120 # seconds
    steps_rate_activity: 300
    missing_computation: True
    max_iterations: 30
    delta_marginal_cost: 0.1
    marginal_cost_tolerance: 100 
    expansion_enabled: False
    cost_transmission_line: 0
    domains: 
      capacity: 
          min: 0
          max: 100000
          step: 200
      transmission: 
          min: -20000
          max: 20000
          step: 200
  output_file_path: solutions/test-2030
