config:
  logging:
    file: ./logs/app.log
    level: DEBUG
  name: SAPP
  name: SAPP-v3
  outline:
    countries:
    - AO
    - BW
    - CD
    - LS
    - MW
    - MZ
    - NA
    - SZ
    - TZ
    - ZA
    - ZM
    - ZW
    years:
    - 2030
    data_file_path: ./osemosys_data/input_data_original/TEMBA_SSP4-60.xlsx
    fuel_code_file_path: ./osemosys_data/fuelcodes(in).csv
    tech_code_file_path: ./osemosys_data/techcodes(in).csv
    representation_per_year: ['M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'M10', 'M11', 'M12'] # Representations inside an year
    timeout_time_step: 180 # seconds
    steps_rate_activity: 300
    missing_computation: True
    max_iterations: 50
    min_convergence_iterations: 5
    delta_marginal_cost: 0.20
    marginal_cost_tolerance: 10
    expansion_enabled: False
    cost_transmission_line: 0
    domains: 
      capacity: 
          min: 0
          max: 100000
          step: 200
      transmission: 
          min: -20000
          max: 20000
          step: 200
  output_file_path: solutions/SAPP-v3-0.2
