config:
  logging:
    file: ./logs/app.log
    level: DEBUG
  name: SAPP-yearly-emissions-10flex-0.2-v3
  outline:
    countries:
    - AO
    - BW
    - CD
    - LS
    - MW
    - MZ
    - NA
    - SZ
    - TZ
    - ZA
    - ZM
    - ZW
    years:
    - 2030
    representation_per_year: ['Y']
    #[ "W1", "W2", "W3", "W4", "W5", "W6", "W7", "W8", "W9", "W10", "W11", "W12", "W13", "W14", "W15", "W16", "W17", "W18", "W19", "W20", "W21", "W22", "W23", "W24", "W25", "W26", "W27", "W28", "W29", "W30", "W31", "W32", "W33", "W34", "W35", "W36", "W37", "W38", "W39", "W40", "W41", "W42", "W43", "W44", "W45", "W46", "W47", "W48", "W49", "W50", "W51", "W52"]
    # ['M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'M10', 'M11', 'M12'] # Representations inside an year
    timeout_time_step: 180 # seconds
    steps_rate_activity: 300
    max_iterations: 100
    min_convergence_iterations: 3
    delta_marginal_cost: 0.20
    marginal_cost_tolerance: 10
    expansion_enabled: False
    cost_transmission_line: 0
    marginal_cost_threshold_percentage: 0.05 #It will double
    domains: 
      capacity: 
          min: 0
          max: 100000
          step: 200
      transmission: 
          min: -20000
          max: 20000
          step: 200
  output_file_path: solutions/SAPP-yearly-emissions-10flex-0.2-v3

  inner_model_configuration:
    AO: 
      scenario:
        opts: [Co2L0.9079-6H] #-9.21

      eletricity:
        automatic_emission: true
        automatic_emission_base_year: 2015
    BW:
      scenario:
        opts: [Co2L0.85-6H] #-15%

      eletricity:
        automatic_emission: true
        automatic_emission_base_year: 2010
    CD:
      eletricity:
        co2limit: 1.4e+7 #t CO2eq.
    LS:
      eletricity:
        co2limit: 1.0e+12 #Infinity
    MW:
      eletricity:
        co2limit: 1.0e+12 #Infinity
    MZ:
      eletricity:
        co2limit: 1.0e+12 #Infinity
    NA:
      eletricity:
        operational_reserve:
          activate: true
          epsilon_vres: 0.95
    SZ:
      eletricity:
        operational_reserve:
          activate: true
          epsilon_vres: 0.50
    TZ:
      eletricity:
        co2limit: 2.8531e+6 #t CO2eq.
    ZA:
      eletricity:
        co2limit: 3.15e+8 #t CO2eq.
    ZM:
      scenario:
        opts: [Co2L0.53-6H] #-47%

      eletricity:
        automatic_emission: true
        automatic_emission_base_year: 2010
    ZW:
      eletricity:
        co2limit: 1.3385e+7 #t CO2eq.


