# -----------------------------------------------------------------------------
# Configuration file for the DMAN-CEP application.
#
# Sections:
#   config: Main configuration block.
#     logging:
#       file: Path to the log file for application logs.
#       level: Logging level (e.g., DEBUG, INFO, WARNING).
#     name: Name identifier for the current scenario or configuration.
#     outline:
#       countries: List of country codes included in the scenario.
#       years: List of years to be simulated.
#       representation_per_year: List of representations per year 
#                                 (e.g., 'Y' for yearly, 
#                                 'M1', 'M2', ... 'M12' for monthly
#                                 'W1', 'W2', ... 'W52' for weekly).
#       max_iterations: Maximum number of iterations for the solver.
#       min_convergence_iterations: Minimum number of iterations required for convergence.
#       delta_marginal_cost: Threshold for marginal cost difference to check convergence.
#       marginal_cost_tolerance: Tolerance value for marginal cost calculations.
#       expansion_enabled: Boolean flag to enable or disable network expansion. (Only False supported currently)
#       cost_transmission_line: Cost assigned to transmission lines (set to 0 to ignore).
#       marginal_cost_threshold_percentage: Percentage threshold for marginal cost (used for doubling).
#     output_file_path: Path where the output solution file will be saved.
#     inner_model_configuration: Placeholder for additional inner model (PyPSA-Earth) settings. Write it per country code.
# -----------------------------------------------------------------------------
config:
  logging:
    file: ./logs/app.log
    level: DEBUG
  name: SAPP-yearly-emissions-nohydrogen-10flex-0.2-v3
  outline:
    countries:
    - AO
    - BW
    - CD
    - LS
    - MW
    - MZ
    - NA
    - SZ
    - TZ
    - ZA
    - ZM
    - ZW
    years:
    - 2030
    representation_per_year: ['Y']
    max_iterations: 100
    min_convergence_iterations: 5
    delta_marginal_cost: 0.20
    marginal_cost_tolerance: 10
    expansion_enabled: False
    cost_transmission_line: 0
    marginal_cost_threshold_percentage: 0.05 #It will double
  output_file_path: solutions/SAPP-yearly-emissions-nohydrogen-10flex-0.2-v3
  
  inner_model_configuration:
    AO: 
      scenario:
        opts: [Co2L0.9079-2H] #-9.21

      eletricity:
        automatic_emission: true
        automatic_emission_base_year: 2015
    BW:
      scenario:
        opts: [Co2L0.85-2H] #-15%

      eletricity:
        automatic_emission: true
        automatic_emission_base_year: 2010
    CD:
      eletricity:
        co2limit: 1.4e+7 #t CO2eq.
    LS:
      eletricity:
        co2limit: 1.0e+12 #Infinity
    MW:
      eletricity:
        co2limit: 1.0e+12 #Infinity
    MZ:
      eletricity:
        co2limit: 1.0e+12 #Infinity
    NA:
      eletricity:
        operational_reserve:
          activate: true
          epsilon_vres: 0.95
    SZ:
      eletricity:
        operational_reserve:
          activate: true
          epsilon_vres: 0.50
    TZ:
      eletricity:
        co2limit: 2.8531e+6 #t CO2eq.
    ZA:
      eletricity:
        co2limit: 3.15e+8 #t CO2eq.
    ZM:
      scenario:
        opts: [Co2L0.53-2H] #-47%

      eletricity:
        automatic_emission: true
        automatic_emission_base_year: 2010
    ZW:
      eletricity:
        co2limit: 1.3385e+7 #t CO2eq.


