name: pypsa-earth-model
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - atlite[version='>=0.4.1']
  - cartopy
  - chaospy
  - contextily
  - country_converter
  - dask
  - earth-osm[version='>=2.3.post1']
  - fake-useragent
  - fiona[version='>=1.10']
  - geopandas[version='>=1']
  - geopy
  - geoviews
  - glpk
  - graphviz
  - gurobi
  - hvplot
  - ipykernel
  - ipython
  - jupyterlab
  - libgdal-core[version='<3.10']
  - libgdal-hdf5
  - lxml
  - matplotlib
  - memory_profiler
  - netcdf4
  - networkx
  - numba
  - numpy[version='<2']
  - openpyxl
  - pandas
  - pip
  - powerplantmatching[version='>=0.5.19']
  - pre-commit
  - py7zr
  - pydoe2
  - pyogrio
  - pypsa[version='>=0.25,<=0.30.3']
  - pyscipopt
  - pytables
  - python[version='>=3.8,<3.12']
  - pytz
  - rasterio
  - reverse-geocode
  - rich
  - rioxarray
  - ruamel.yaml[version='<=0.17.26']
  - scipy[version='<1.16']
  - seaborn
  - shapely!=2.0.4
  - snakemake-minimal[version='<8']
  - tqdm
  - tsam[version='>=1.1.0']
  - xarray[version='>=2023.11.0,<=2025.01.2']
  - xlrd
prefix: /opt/miniconda3/envs/pypsa-earth-model
